name: jplayer
description: A Flutter media player application with video and audio support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.0
  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true