name: jplayer
description: A complete media player like VLC for Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Video player
  video_player: ^2.8.2
  
  # Audio player
  audioplayers: ^5.2.1
  
  # Permissions
  permission_handler: ^11.2.0
  
  # File system
  path_provider: ^2.1.2
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true